clusterName: ""
defaultCRConfig:
  presets:
    resourceDetection:
      aks:
        enabled: true
instrumentation:
  resource:
    resourceAttributes:
      deployment.environment.name: "production"