apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-rest-go
  labels:
    app.kubernetes.io/name: calendar-rest-go
    app.kubernetes.io/instance: calendar-rest-go
    app: calendar-rest-go
spec:
  selector:
    matchLabels:
      app: calendar-rest-go
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calendar-rest-go
        app.kubernetes.io/name: calendar-rest-go
        app.kubernetes.io/instance: calendar-rest-go
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: ng-experiment-1
      containers:
        - name: calendar-rest-go
          image: dineshgurumurthydd/apps:calendar-go-rest-0.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 800m
              memory: 800Mi
          livenessProbe:
            timeoutSeconds: 2
            httpGet:
              path: /calendar
              port: http
          readinessProbe:
            timeoutSeconds: 2
            httpGet:
              path: /calendar
              port: http
          env:
            - name: OTEL_SERVICE_NAME
              value: calendar-rest-go
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_GRPC_PORT
              value: "4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://$(HOST_IP):$(OTLP_GRPC_PORT)'
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: >-
                service.name=$(OTEL_SERVICE_NAME), k8s.namespace.name=$(OTEL_K8S_NAMESPACE), k8s.node.name=$(OTEL_K8S_NODE_NAME), k8s.pod.name=$(OTEL_K8S_POD_NAME), deployment.environment=$(OTEL_K8S_NAMESPACE)
          ports:
            - containerPort: 9090
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-rest-go
  labels:
    app.kubernetes.io/name: calendar-rest-go
    app.kubernetes.io/instance: calendar-rest-go
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: calendar-rest-go
    app.kubernetes.io/instance: calendar-rest-go
---
