receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  datadog:
    hostname: "otelcol-docker"
    api:
      key: ${DD_API_KEY}


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ batch]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]

