receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
  filelog:
    include:
      - log.json
    include_file_path: true
    include_file_path_resolved: true
    include_file_name_resolved: true
    start_at: end
    poll_interval: 500ms
    operators:
      # Detect pod, namespace, and container names from the file name.
      - id: parse_body
        type: json_parser

exporters:
  debug:
    verbosity: detailed
  datadog/api:
    host_metadata:
      tags:
        - otlp:true
        - example:tag
    api:
      key: "${DD_API_KEY}"

connectors:
  datadog/connector:

processors:
  batch:
    timeout: 10s
  resourcedetection:
    detectors: [system]

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, datadog/connector]
      processors: [batch, resourcedetection]
      exporters: [datadog/api]
    traces/sampling:
      receivers: [datadog/connector]
      processors: [] # Add any sampling here
      exporters: [datadog/api]
    traces:
      receivers: [otlp]
      processors: [batch,resourcedetection]
      exporters: [debug, datadog/connector]
    logs:
      receivers: [filelog]
      processors: [batch, resourcedetection]
      exporters: [datadog/api]
