{{- if and .Values.global.useSpanMetricsConnectorNoRouting (not .Values.global.useOtlpIntake) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-config
  labels:
    app.kubernetes.io/name: otel-config
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      hostmetrics:
        # collect metrics every 10 seconds.
        collection_interval: 10s
        scrapers:
          cpu:
          disk:
          filesystem:
          memory:
          network:
          load:
          paging:
          processes:

    exporters:
      datadog/exporter:
        api:
          site: ${env:DD_SITE}
          key: ${env:DD_API_KEY}
      otlphttp:
        headers:
          "Dd-Api-Key": ${env:DD_API_KEY}
          "dd-otel-metric-config": '{"trace_metrics": {"instrumentation_metrics_calc": true, "namespace": "traces.span.metrics."}, "raw_instrumentation_metrics_drop": false}'
        metrics_endpoint: {{ .Values.otelCollector.datadog.otlpMetricsEndpoint }}
      debug:
        verbosity: detailed

    connectors:
      spanmetrics:
        aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
        add_resource_attributes: true
        dimensions:
          # env
          - name: deployment.environment.name

          # version
          - name: service.version

          # status code
          - name: http.response.status_code

          # all inputs for host
          - name: host
          - name: aws.ecs.launchtype
          - name: aws.ecs.task.arn
          - name: cloud.provider
          - name: cloud.account.id
          - name: host.id
          - name: host.name
          - name: k8s.node.name
          - name: k8s.cluster.name
          - name: azure.resourcegroup.name

          # peer tags
          - name: aws.sqs.queue.url
          - name: aws.s3.bucket
          - name: db.hostname
          - name: db.namespace
          - name: db.system.name
          - name: messaging.destination.name
          - name: messaging.system
          - name: service.peer.name
          - name: rpc.method
          - name: rpc.system.name
          - name: server.address

          # container tags
          - name: container.id
          - name: container.name
          - name: container.image.name
          - name: container.image.tag
          - name: container.runtime
          - name: cloud.region
          - name: cloud.availability_zone
          - name: aws.ecs.task.family
          - name: aws.ecs.cluster.arn
          - name: aws.ecs.task.revision
          - name: aws.ecs.container.arn
          - name: k8s.container.name
          - name: k8s.deployment.name
          - name: k8s.replicaset.name
          - name: k8s.statefulset.name
          - name: k8s.daemon.set.name
          - name: k8s.job.name
          - name: k8s.cronjob.name
          - name: k8s.namespace.name
          - name: k8s.pod.name

          # all inputs for operation name
          - name: operation.name
          - name: http.request.method
          - name: http.method
          - name: db.system
          - name: messaging.operation
          - name: rpc.system
          - name: rpc.service
          - name: faas.invoked_provider
          - name: faas.invoked_name
          - name: faas.trigger
          - name: graphql.operation.type
          - name: network.protocol.name

          # all inputs for resource name
          - name: resource.name
          - name: http.route
          - name: messaging.destination
          - name: graphql.operation.name
          - name: db.statement
          - name: db.query.text

    processors:
      batch:
      cumulativetodelta:
        include:
          match_type: regexp
          metrics:
            - .*
      transform/unit:
        metric_statements:
        - context: datapoint
          statements:
            - set(metric.unit, "ms") where metric.name == "http.server.duration" or metric.name == "http.client.duration" or metric.name == "http.server.request.duration"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog/exporter, spanmetrics]

        metrics/spanmetricsconnector:
          receivers: [spanmetrics]
          processors: [cumulativetodelta, transform/unit]
          exporters: [otlphttp, debug]
        metrics:
          receivers: [otlp]
          processors: [cumulativetodelta, transform/unit]
          exporters: [otlphttp, debug]
{{- end }}
