dist:
  name: otelcol-custom
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-custom
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.115.0
    path: /Users/john.peterson/otel/opentelemetry-collector-contrib/exporter/datadogexporter
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.115.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.115.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.21.0
replaces:
  - "github.com/DataDog/datadog-agent/pkg/trace => /Users/john.peterson/go/src/github.com/DataDog/datadog-agent/pkg/trace"
