clusterName: "my_k8s_cluster"
defaultCRConfig:
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secret
          key: api-key
    - name: DD_SITE
      value: datadoghq.eu
    - name: OTEL_K8S_CLUSTER_NAME
      value: "my_k8s_cluster"
  presets:
    resourceDetection:
      aks:
        enabled: false
      eks:
        enabled: false
      gcp:
        enabled: false
collectors:
  daemon:
    presets:
      resourceDetection:
        aks:
          enabled: false
        eks:
          enabled: false
        gcp:
          enabled: false
instrumentation:
  resource:
    resourceAttributes:
      deployment.environment.name: "production"