apiVersion: v1
kind: Namespace
metadata:
  name: astronomy-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: astronomy-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: opentelemetry-operator-system/opentelemetry-kube-stack
        resource.opentelemetry.io/service-name: frontend
        resource.opentelemetry.io/service-namespace: astronomy-store
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          image: astronomy-store/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PRODUCT_CATALOG_URL
              value: http://product-catalog:8080
            - name: AD_URL
              value: http://ad:8080
            - name: CHECKOUT_URL
              value: http://checkout:8080
          readinessProbe:
            httpGet:
              path: /api/products
              port: http
          livenessProbe:
            httpGet:
              path: /api/products
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: astronomy-store
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
