apiVersion: v1
kind: Namespace
metadata:
  name: astronomy-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: astronomy-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-detection
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: opentelemetry-operator-system/opentelemetry-kube-stack
        resource.opentelemetry.io/service-name: fraud-detection
        resource.opentelemetry.io/service-namespace: astronomy-store
      labels:
        app.kubernetes.io/name: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: astronomy-store/fraud-detection:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: astronomy-store
spec:
  selector:
    app.kubernetes.io/name: fraud-detection
  ports:
    - name: http
      port: 8080
      targetPort: http
