apiVersion: v1
kind: Namespace
metadata:
  name: astronomy-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: astronomy-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fraud-detection
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: opentelemetry-operator-system/opentelemetry-kube-stack
        resource.opentelemetry.io/service-name: fraud-detection
        resource.opentelemetry.io/service-namespace: astronomy-store
      labels:
        app.kubernetes.io/name: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: astronomy-store/fraud-detection:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_ADDR
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: orders
