enabled: true
mode: deployment

# Enabling presets automatically configures the necessary service accounts
# and sane defaults
presets:
  clusterMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true

extraEnvs:
  - name: DD_API_KEY
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key

clusterRole:
  rules:
    - apiGroups:
        - ""
      resources:
        - events
        - endpoints
        - namespaces
        - namespaces/status
        - nodes
        - nodes/spec
        - nodes/stats
        - pods
        - pods/status
        - replicationcontrollers
        - replicationcontrollers/status
        - resourcequotas
        - services
        - persistentvolumes
        - persistentvolumeclaims
        - serviceaccounts
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - policy
      resources:
        - poddisruptionbudgets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources:
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
        - cronjobs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - autoscaling
      resources:
        - horizontalpodautoscalers
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - rbac.authorization.k8s.io
      resources:
        - roles
        - rolebindings
        - clusterroles
        - clusterrolebindings
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - "storage.k8s.io"
      resources:
        - storageclasses
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - autoscaling.k8s.io
      resources:
        - verticalpodautoscalers
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - "autoscaling"
      resources:
        - horizontalpodautoscalers
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - "networking.k8s.io"
      resources:
        - networkpolicies
        - ingresses
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - apiextensions.k8s.io
      resources:
        - customresourcedefinitions
      verbs:
        - get
        - list
        - watch

config:
  receivers:
    k8s_cluster:
      auth_type: serviceAccount
    
    # Prometheus receiver is used to scrape kube state metrics
    prometheus:
      config:
        scrape_configs:
          - job_name: 'kube-state-metrics'
            metrics_path: /metrics
            scheme: http
            static_configs:
              - targets:
                  - kube-state-metrics.default.svc:8080
            metric_relabel_configs:
              - source_labels: [__name__]
                regex: 'kube_daemonset_.*|kube_deployment_.*|kube_job_.*|kube_node_.*|kube_pod_.*|kube_replicaset_.*|kube_statefulset_.*|kube_service_spec_type'
                action: keep

    # orchestrator check
    k8sobjects:
      auth_type: serviceAccount
      objects:
        - name: namespaces
          mode: pull
          interval: 3m
        - name: namespaces
          mode: watch
        - name: pods
          mode: pull
          interval: 3m
        - name: pods
          mode: watch
        - name: nodes
          mode: pull
          interval: 3m
        - name: nodes
          mode: watch
        - name: replicasets
          mode: pull
          interval: 3m
        - name: replicasets
          mode: watch
        - name: daemonsets
          mode: pull
          interval: 3m
        - name: daemonsets
          mode: watch
        - name: statefulsets
          mode: pull
          interval: 3m
          group: apps
        - name: statefulsets
          mode: watch
          group: apps
        - name: cronjobs
          mode: pull
          interval: 3m
        - name: cronjobs
          mode: watch
        - name: jobs
          mode: pull
          interval: 3m
        - name: jobs
          mode: watch
        - name: services
          mode: pull
          interval: 3m
        - name: services
          mode: watch
        - name: deployments
          mode: pull
          interval: 3m
          group: apps
        - name: deployments
          mode: watch
          group: apps
        - name: roles
          mode: pull
          interval: 3m
          group: rbac.authorization.k8s.io
        - name: roles
          mode: watch
          group: rbac.authorization.k8s.io
        - name: rolebindings
          mode: pull
          interval: 3m
          group: rbac.authorization.k8s.io
        - name: rolebindings
          mode: watch
          group: rbac.authorization.k8s.io
        - name: clusterroles
          mode: pull
          interval: 3m
          group: rbac.authorization.k8s.io
        - name: clusterroles
          mode: watch
          group: rbac.authorization.k8s.io
        - name: clusterrolebindings
          mode: pull
          interval: 3m
          group: rbac.authorization.k8s.io
        - name: clusterrolebindings
          mode: watch
          group: rbac.authorization.k8s.io
        - name: storageclasses
          mode: pull
          interval: 3m
          group: storage.k8s.io
        - name: storageclasses
          mode: watch
          group: storage.k8s.io
        - name: networkpolicies
          mode: pull
          interval: 3m
          group: networking.k8s.io
        - name: networkpolicies
          mode: watch
          group: networking.k8s.io
        - name: ingresses
          mode: pull
          interval: 3m
          group: networking.k8s.io
        - name: ingresses
          mode: watch
          group: networking.k8s.io
        - name: persistentvolumes
          mode: pull
          interval: 3m
        - name: persistentvolumes
          mode: watch
        - name: persistentvolumeclaims
          mode: pull
          interval: 3m
        - name: persistentvolumeclaims
          mode: watch
        - name: poddisruptionbudgets
          mode: pull
          interval: 3m
          group: policy
        - name: poddisruptionbudgets
          mode: watch
          group: policy
        - name: serviceaccounts
          mode: pull
          interval: 3m
        - name: serviceaccounts
          mode: watch
        - name: horizontalpodautoscalers
          mode: pull
          interval: 3m
          group: autoscaling
        - name: horizontalpodautoscalers
          mode: watch
          group: autoscaling
        - name: customresourcedefinitions
          mode: pull
          interval: 3m
          group: apiextensions.k8s.io
        - name: customresourcedefinitions
          mode: watch
          group: apiextensions.k8s.io
        # Uncomment it if VPA CRD is installed
        # - name: verticalpodautoscalers
        #   mode: pull
        #   interval: 3m
        #   group: autoscaling.k8s.io
        # - name: verticalpodautoscalers
        #   mode: watch
        #   group: autoscaling.k8s.io
  
  processors:
    cumulativetodelta: {}

    # Rename KSM metric prometheus label uid -> k8s.pod.uid to adhere to OTel standard and
    # facililtate the groupby specified below.
    transform/rename_uid:
      metric_statements:
        - context: datapoint
          statements:
            - set(attributes["k8s.pod.uid"], attributes["uid"])
            - delete_key(attributes, "uid")
        # We have to delete these from the resource because they were incorrectly 
        # set by the prometheus receiver, k8sattributes will repopulate them but
        # cannot overwrite them.
        - context: resource
          statements:
            - delete_key(attributes, "service.name")
            - delete_key(attributes, "service.instance.id")
    
    # Grouping by k8s.pod.uid (a globally unique ID) correctly associates the
    # kube-state-metrics pod metrics with their respective OTel resources.
    groupbyattrs:
      keys:
        - k8s.pod.uid

    # Modify kube-state-metric Datapoint attributes so that they adhere to Datadog's
    # expected schema.
    transform/ksm_to_dd:
      metric_statements:
        - context: datapoint
          statements:
            # statefulset
            - set(attributes["kube_namespace"], attributes["namespace"])
            - delete_key(attributes, "namespace")

            # statefulset
            - set(attributes["kube_deployment"], attributes["deployment"])
            - delete_key(attributes, "deployment")

            # phase
            - set(attributes["pod_phase"], attributes["phase"])
            - delete_key(attributes, "phase")

            # statefulset
            - set(attributes["kube_stateful_set"], attributes["statefulset"])
            - delete_key(attributes, "statefulset")

            # daemonset
            - set(attributes["kube_daemon_set"], attributes["daemonset"])
            - delete_key(attributes, "daemonset")

            # replicaset
            - set(attributes["kube_replica_set"], attributes["replicaset"])
            - delete_key(attributes, "replicaset")

            # job_name
            - set(attributes["kube_job"], attributes["job_name"])
            - delete_key(attributes, "job_name")

            # service
            - set(attributes["kube_service"], attributes["service"])
            - delete_key(attributes, "service")
    
    # k8sattributesprocessor is used to enrich metrics with additional metadata, namely, service.
    k8sattributes:
      auth_type: "serviceAccount"
      extract:
        otel_annotations: true
        metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.replicaset.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.container.name
          - service.name
          - service.version
          - service.instance.id
      passthrough: false
      # By default association is done via Pod IP, we need to override
      # this so it doesn't erroneously associate metrics with the 
      # kube-state-metrics pod.
      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.uid
    
    transform/sum_to_gauge:
      metric_statements:
        - convert_sum_to_gauge() where metric.name == "k8s.service.count"
        - convert_sum_to_gauge() where metric.name == "k8s.node.count"
        - convert_sum_to_gauge() where metric.name == "k8s.job.count"

    # Drop metric after count connector has used it
    filter/ksm:
      metrics:
        metric:
          - metric.name == "kube_service_spec_type"

    # Inject k8s.cluster.uid by detector: kubeadm, which is required by orchestrator check
    # Inject k8s.cluster.name by automatic cluster name detection,
    # Adjust the `k8s.cluster.name` section for your cloud provider.
    # See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.152.0/processor/resourcedetectionprocessor#amazon-eks
    resourcedetection:
      detectors: [env, kubeadm, eks, ec2, aks, azure, gcp, system]
      override: false
      kubeadm:
        resource_attributes:
          k8s.cluster.name:
            enabled: false
      eks:
        resource_attributes:
          k8s.cluster.name:
            enabled: true
      aks:
        resource_attributes:
          k8s.cluster.name:
            enabled: true
    
    # # Optional: manually inject the cluster name if the resourcedetection processor does not support your cloud provider.
    # resource:
    #       attributes:
    #         - key: k8s.cluster.name
    #           value: <YOUR K8S CLUSTER NAME HERE>
    #           action: upsert
  
  connectors:
    # The count connector helps us generate three custom metrics by counting the number 
    # of metric series. It generates the following metrics:
    # 1. k8s.service.count
    # 2. k8s.node.count
    # 3. k8s.job.count
    count:
      aggregation_interval: 10s
      datapoints:
        k8s.service.count:
          # k8s.service.count is grouped by namespace and type
          # so we have to grab those attributes from the original metric.
          attributes:
            - key: namespace
              default_value: unspecified_namespace
            - key: type
              default_value: unspecified_service_type
          conditions:
            - metric.name == "kube_service_spec_type"

        k8s.node.count:
          conditions:
            - metric.name == "kube_node_info"

        k8s.job.count:
          conditions:
            - metric.name == "kube_job_owner"

  exporters:
    datadog/exporter:
      api:
        key: ${env:DD_API_KEY}
      orchestrator_explorer:
          enabled: true
  
  service:
    extensions: [health_check]
    pipelines:
      logs/orchestrator:
        receivers: [k8sobjects]
        processors: [resourcedetection]
        exporters: [datadog/exporter]
      
      metrics/count:
        receivers: [prometheus]
        exporters: [count]
        
      metrics:
        receivers: [otlp, prometheus, count]
        processors: [filter/ksm, resourcedetection, transform/ksm_to_dd, transform/rename_uid, groupbyattrs, k8sattributes, cumulativetodelta, transform/sum_to_gauge]
        exporters: [datadog/exporter]
