apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calendar.fullname" . }}
  labels:
    tags.datadoghq.com/env: {{ .Values.env }}
    tags.datadoghq.com/service: {{ include "calendar.fullname" . }}
    tags.datadoghq.com/version: {{ .Values.image.tag }}
    {{- include "calendar.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      tags.datadoghq.com/env: {{ .Values.env }}
      tags.datadoghq.com/service: {{ include "calendar.fullname" . }}
      tags.datadoghq.com/version: {{ .Values.image.tag }}
      {{- include "calendar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        tags.datadoghq.com/env: {{ .Values.env }}
        tags.datadoghq.com/service: {{ include "calendar.fullname" . }}
        tags.datadoghq.com/version: {{ .Values.image.tag }}
        {{- include "calendar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /calendar
              port: http
          readinessProbe:
            httpGet:
              path: /calendar
              port: http
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ include "calendar.fullname" . }}
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
               fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_GRPC_PORT
              value: "4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://$(HOST_IP):$(OTLP_GRPC_PORT)'
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: 'grpc'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
