// Command generate renders values-ddot.yaml and values-otlp-http.yaml from
// ../values.yaml.tmpl, one per exporter mode. Run via `make
// generate-base-values` (cds into this directory first).
package main

import (
	"fmt"
	"os"
	"text/template"
)

type mode struct {
	name   string
	ddot   bool
	banner string
}

var modes = []mode{
	{
		name: "ddot", ddot: true,
		banner: "# DDOT mode: native Datadog exporter/connector, full feature parity, +\n" +
			"# DDOT-flavored auto-instrumentation SDKs.",
	},
	{
		name: "otlp-http", ddot: false,
		banner: "# OTLP/HTTP mode: vendor-neutral protocol to Datadog's OTLP intake +\n" +
			"# upstream OpenTelemetry auto-instrumentation SDKs.",
	},
}

func render(tmpl *template.Template, m mode) error {
	out, err := os.Create("../values-" + m.name + ".yaml")
	if err != nil {
		return err
	}
	defer out.Close()

	exporter := "otlp_http"
	if m.ddot {
		exporter = "datadog/exporter"
	}

	fmt.Fprintf(out, "# Code generated by `make generate-base-values` from values.yaml.tmpl.\n"+
		"# DO NOT EDIT directly — edit that file instead and re-run\n"+
		"# `make generate-base-values`.\n\n")
	return tmpl.Execute(out, map[string]any{
		"Ddot":     m.ddot,
		"Exporter": exporter,
		"Banner":   m.banner,
	})
}

func main() {
	tmpl := template.Must(template.ParseFiles("../values.yaml.tmpl"))
	for _, m := range modes {
		if err := render(tmpl, m); err != nil {
			fmt.Fprintf(os.Stderr, "failed to render values-%s.yaml: %s\n", m.name, err)
			os.Exit(1)
		}
	}
}
