receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  datadog:
    hostname: "otelcol-docker"
    api:
      key: ${DD_API_KEY}

connectors:
  datadog/connector:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/connector]
    traces/sampling:
      receivers: [datadog/connector]
      processors: []
      exporters: [datadog]
    metrics:
      receivers: [otlp, datadog/connector]
      processors: [batch]
      exporters: [datadog]

