clusterName: ""
defaultCRConfig:
  presets:
    resourceDetection:
      eks:
        enabled: true
collectors:
  daemon:
    presets:
      resourceDetection:
        eks:
          enabled: true
instrumentation:
  resource:
    resourceAttributes:
      deployment.environment.name: "production"