# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
FROM golang:1.24

WORKDIR /app
COPY app_server log-correlation-go-server/

WORKDIR /app/log-correlation-go-server
RUN go mod download

RUN go build -o /log-correlation-go-server

CMD [ "/log-correlation-go-server" ]
