# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
FROM golang:1.20

WORKDIR /app
COPY app_client log-correlation-go-client/

WORKDIR /app/log-correlation-go-client
RUN go mod download

RUN go build -o /log-correlation-go-client

CMD [ "/log-correlation-go-client" ]
