# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
FROM golang:1.20


WORKDIR /app
COPY calendar-consumer-go-otel calendar/

WORKDIR /app/calendar
RUN go mod download

RUN go build -o /calendar

CMD [ "/calendar" ]
