// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: gameoflife.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_UNKNOWN     ResponseCode = 0
	ResponseCode_OK          ResponseCode = 1
	ResponseCode_BAD_REQUEST ResponseCode = 2
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "BAD_REQUEST",
	}
	ResponseCode_value = map[string]int32{
		"UNKNOWN":     0,
		"OK":          1,
		"BAD_REQUEST": 2,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gameoflife_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_gameoflife_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_gameoflife_proto_rawDescGZIP(), []int{0}
}

type GameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board   string `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	NumGens int32  `protobuf:"varint,2,opt,name=num_gens,json=numGens,proto3" json:"num_gens,omitempty"`
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameoflife_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameoflife_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_gameoflife_proto_rawDescGZIP(), []int{0}
}

func (x *GameRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *GameRequest) GetNumGens() int32 {
	if x != nil {
		return x.NumGens
	}
	return 0
}

type GameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=gameoflifepb.ResponseCode" json:"code,omitempty"`
	ErrorMessage string       `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Board        string       `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameoflife_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameoflife_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_gameoflife_proto_rawDescGZIP(), []int{1}
}

func (x *GameResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_UNKNOWN
}

func (x *GameResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GameResponse) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

var File_gameoflife_proto protoreflect.FileDescriptor

var file_gameoflife_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x6f, 0x66, 0x6c, 0x69, 0x66, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x6f, 0x66, 0x6c, 0x69, 0x66, 0x65, 0x70, 0x62,
	0x22, 0x3e, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x67, 0x65, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x47, 0x65, 0x6e, 0x73,
	0x22, 0x79, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6f, 0x66, 0x6c, 0x69, 0x66, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2a, 0x34, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x02, 0x32, 0x4e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x66, 0x4c, 0x69, 0x66, 0x65, 0x12,
	0x40, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x6f, 0x66, 0x6c, 0x69, 0x66, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x6f, 0x66, 0x6c, 0x69,
	0x66, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x67, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x61,
	0x70, 0x70, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x6f, 0x66, 0x2d, 0x6c, 0x69, 0x66, 0x65,
	0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gameoflife_proto_rawDescOnce sync.Once
	file_gameoflife_proto_rawDescData = file_gameoflife_proto_rawDesc
)

func file_gameoflife_proto_rawDescGZIP() []byte {
	file_gameoflife_proto_rawDescOnce.Do(func() {
		file_gameoflife_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameoflife_proto_rawDescData)
	})
	return file_gameoflife_proto_rawDescData
}

var file_gameoflife_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gameoflife_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gameoflife_proto_goTypes = []interface{}{
	(ResponseCode)(0),    // 0: gameoflifepb.ResponseCode
	(*GameRequest)(nil),  // 1: gameoflifepb.GameRequest
	(*GameResponse)(nil), // 2: gameoflifepb.GameResponse
}
var file_gameoflife_proto_depIdxs = []int32{
	0, // 0: gameoflifepb.GameResponse.code:type_name -> gameoflifepb.ResponseCode
	1, // 1: gameoflifepb.GameOfLife.RunGame:input_type -> gameoflifepb.GameRequest
	2, // 2: gameoflifepb.GameOfLife.RunGame:output_type -> gameoflifepb.GameResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gameoflife_proto_init() }
func file_gameoflife_proto_init() {
	if File_gameoflife_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameoflife_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameoflife_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameoflife_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameoflife_proto_goTypes,
		DependencyIndexes: file_gameoflife_proto_depIdxs,
		EnumInfos:         file_gameoflife_proto_enumTypes,
		MessageInfos:      file_gameoflife_proto_msgTypes,
	}.Build()
	File_gameoflife_proto = out.File
	file_gameoflife_proto_rawDesc = nil
	file_gameoflife_proto_goTypes = nil
	file_gameoflife_proto_depIdxs = nil
}
