# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
FROM golang:1.20


WORKDIR /app
COPY words-consumer-go-otel words/

WORKDIR /app/words
RUN go mod download; go build -o /calendar

CMD [ "/calendar" ]
