# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env

WORKDIR /home/otel
COPY RandomDateAPIOTel RandomDateAPI/

WORKDIR /home/otel/RandomDateAPI
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /home/otel/RandomDateAPI
COPY --from=build-env /home/otel/RandomDateAPI/out .

ENTRYPOINT ["dotnet","RandomDateAPI.dll"]
EXPOSE 5077
