apiVersion: v1
kind: Namespace
metadata:
  name: astronomy-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  namespace: astronomy-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ad
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: opentelemetry-operator-system/opentelemetry-kube-stack
        resource.opentelemetry.io/service-name: ad
        resource.opentelemetry.io/service-namespace: astronomy-store
      labels:
        app.kubernetes.io/name: ad
    spec:
      containers:
        - name: ad
          image: astronomy-store/ad:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://astronomy-db:5432/astronomy_db
            - name: DB_USERNAME
              value: astronomy_user
            - name: DB_PASSWORD
              value: astronomy_password
          readinessProbe:
            httpGet:
              path: /ad/health
              port: http
          livenessProbe:
            httpGet:
              path: /ad/health
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: astronomy-store
spec:
  selector:
    app.kubernetes.io/name: ad
  ports:
    - name: http
      port: 8080
      targetPort: http
